name = "cloudrouter"
main = "src/index.js"
compatibility_date = "2023-09-01"

[[kv_namespaces]]
binding = "ROUTER_KV"
id = "your-kv-id" # 部署时需要替换为实际的KV命名空间ID

[vars]
AUTH_KEY = "your-auth-key" # 部署时可以修改为自定义的认证密钥 